#!/usr/bin/env bash

NAME=$1

groupadd --force sandbox

useradd                         \
  --base-dir /var/sandbox/home  \
  --gid      sandbox            \
  --skel     /var/sandbox/skel  \
  --key      MAIL_DIR=/dev/null \
  --shell    /var/sandbox/shell \
  --create-home                 \
  --no-user-group               \
  $NAME
